// This file is auto-generated by scripts/generate-types.js
// Do not edit this file directly.
import type { Tables } from "@/database.types";

// =============================================
// ================ TABLE TYPES ================
// =============================================

// --- ATTEMPTS ---
export type Attempt = Tables<'attempts'>;
// --- CHATS ---
export type Chat = Tables<'chats'>;
// --- COMPANY_CODES ---
export type CompanyCode = Tables<'company_codes'>;
// --- CONTACT_MESSAGES ---
export type ContactMessage = Tables<'contact_messages'>;
// --- DOCUMENTS ---
export type Document = Tables<'documents'>;
// --- EMAIL_SUBSCRIPTIONS ---
export type EmailSubscription = Tables<'email_subscriptions'>;
// --- FIELDS ---
export type Field = Tables<'fields'>;
// --- GET_STARTED_SUBMISSIONS ---
export type GetStartedSubmission = Tables<'get_started_submissions'>;
// --- GROUPS ---
export type Group = Tables<'groups'>;
// --- HINTS ---
export type Hint = Tables<'hints'>;
// --- LOGS ---
export type Log = Tables<'logs'>;
// --- MESSAGES ---
export type Message = Tables<'messages'>;
// --- PARAMETERS ---
export type Parameter = Tables<'parameters'>;
// --- PERSONAS ---
export type Persona = Tables<'personas'>;
// --- POLICIES ---
export type Policy = Tables<'policies'>;
// --- PROFILES ---
export type Profile = Tables<'profiles'>;
// --- RUBRIC_GRADES ---
export type RubricGrade = Tables<'rubric_grades'>;
// --- RUBRICS ---
export type Rubric = Tables<'rubrics'>;
// --- SCENARIOS ---
export type Scenario = Tables<'scenarios'>;
// --- STANDARD_GRADES ---
export type StandardGrade = Tables<'standard_grades'>;
// --- STANDARDS ---
export type Standard = Tables<'standards'>;
// --- TRAININGS ---
export type Training = Tables<'trainings'>;
// --- USER_ADDITION_REQUESTS ---
export type UserAdditionRequest = Tables<'user_addition_requests'>;
// --- USER_FEEDBACK ---
export type UserFeedback = Tables<'user_feedback'>;
// --- USER_INSIGHTS ---
export type UserInsight = Tables<'user_insights'>;

// =============================================
// ================ ENUM TYPES ================
// =============================================

export type FieldType = "persona" | "document" | "numerical" | "categorical" | "text";
export type InterviewType = "regular" | "cheating" | "ai-assisted";
export type Level = "junior" | "mid" | "senior" | "executive";
export type LogLevel = "info" | "error" | "warn" | "debug";
export type MessageRole = "user" | "assistant";
export type QuestionType = "mcq" | "frq";
export type TrainingType = "interview" | "offboarding";
export type UserRole = "employee" | "admin" | "superadmin";

// =============================================
// ============= UTILITY TYPES =============
// =============================================

// Union type of all table names
export type TableName = 'attempts' | 'chats' | 'company_codes' | 'contact_messages' | 'documents' | 'email_subscriptions' | 'fields' | 'get_started_submissions' | 'groups' | 'hints' | 'logs' | 'messages' | 'parameters' | 'personas' | 'policies' | 'profiles' | 'rubric_grades' | 'rubrics' | 'scenarios' | 'standard_grades' | 'standards' | 'trainings' | 'user_addition_requests' | 'user_feedback' | 'user_insights';

// Union type of all entity types
export type Entity = Attempt | Chat | CompanyCode | ContactMessage | Document | EmailSubscription | Field | GetStartedSubmission | Group | Hint | Log | Message | Parameter | Persona | Policy | Profile | RubricGrade | Rubric | Scenario | StandardGrade | Standard | Training | UserAdditionRequest | UserFeedback | UserInsight;
