// This file is auto-generated by scripts/generate-types.js
// Do not edit this file directly.
import type { Tables } from "@/database.types";

// =============================================
// ================ TABLE TYPES ================
// =============================================

// --- ASSESSMENTS ---
export type Assessment = Tables<"assessments">;
// --- ATTEMPTS ---
export type Attempt = Tables<"attempts">;
// --- CHATS ---
export type Chat = Tables<"chats">;
// --- DOCUMENTS ---
export type Document = Tables<"documents">;
// --- FEEDBACK ---
export type Feedback = Tables<"feedback">;
// --- FIELDS ---
export type Field = Tables<"fields">;
// --- GROUPS ---
export type Group = Tables<"groups">;
// --- HINTS ---
export type Hint = Tables<"hints">;
// --- LOGS ---
export type Log = Tables<"logs">;
// --- MESSAGES ---
export type Message = Tables<"messages">;
// --- PARAMETERS ---
export type Parameter = Tables<"parameters">;
// --- PERSONAS ---
export type Persona = Tables<"personas">;
// --- PROFILES ---
export type Profile = Tables<"profiles">;
// --- QUESTIONS ---
export type Question = Tables<"questions">;
// --- RUBRIC_GRADES ---
export type RubricGrade = Tables<"rubric_grades">;
// --- RUBRICS ---
export type Rubric = Tables<"rubrics">;
// --- SCENARIOS ---
export type Scenario = Tables<"scenarios">;
// --- STANDARD_GRADES ---
export type StandardGrade = Tables<"standard_grades">;
// --- STANDARDS ---
export type Standard = Tables<"standards">;
// --- TRAININGS ---
export type Training = Tables<"trainings">;
// --- USER_FEEDBACK ---
export type UserFeedback = Tables<"user_feedback">;
// --- USER_INSIGHTS ---
export type UserInsight = Tables<"user_insights">;

// =============================================
// ================ ENUM TYPES ================
// =============================================

export type FieldType =
  | "persona"
  | "document"
  | "numerical"
  | "categorical"
  | "text";
export type InterviewType = "regular" | "cheating" | "ai-assisted";
export type Level = "junior" | "mid" | "senior" | "executive";
export type LogLevel = "info" | "error" | "warn" | "debug";
export type MessageRole = "user" | "assistant";
export type QuestionType = "mcq" | "frq";
export type TrainingType = "interview" | "offboarding";
export type UserRole = "employee" | "admin" | "superadmin";

// =============================================
// ============= UTILITY TYPES =============
// =============================================

// Union type of all table names
export type TableName =
  | "assessments"
  | "attempts"
  | "chats"
  | "documents"
  | "feedback"
  | "fields"
  | "groups"
  | "hints"
  | "logs"
  | "messages"
  | "parameters"
  | "personas"
  | "profiles"
  | "questions"
  | "rubric_grades"
  | "rubrics"
  | "scenarios"
  | "standard_grades"
  | "standards"
  | "trainings"
  | "user_feedback"
  | "user_insights";

// Union type of all entity types
export type Entity =
  | Assessment
  | Attempt
  | Chat
  | Document
  | Feedback
  | Field
  | Group
  | Hint
  | Log
  | Message
  | Parameter
  | Persona
  | Profile
  | Question
  | RubricGrade
  | Rubric
  | Scenario
  | StandardGrade
  | Standard
  | Training
  | UserFeedback
  | UserInsight;
