// This file is auto-generated by scripts/generate-types.js
// Do not edit this file directly.
import type { Tables } from "@/database.types";

// =============================================
// ================ TABLE TYPES ================
// =============================================

// --- ASSESSMENTS ---
export type Assessment = Tables<'assessments'>;
// --- CHATS ---
export type Chat = Tables<'chats'>;
// --- FEEDBACK ---
export type Feedback = Tables<'feedback'>;
// --- LOGS ---
export type Log = Tables<'logs'>;
// --- MESSAGES ---
export type Message = Tables<'messages'>;
// --- RESUMES ---
export type Resume = Tables<'resumes'>;

// =============================================
// ================ ENUM TYPES ================
// =============================================

export type InterviewType = "regular" | "cheating" | "ai-assisted";
export type LogLevel = "info" | "error" | "warn" | "debug";
export type MessageRole = "user" | "assistant";

// =============================================
// ============= UTILITY TYPES =============
// =============================================

// Union type of all table names
export type TableName = 'assessments' | 'chats' | 'feedback' | 'logs' | 'messages' | 'resumes';

// Union type of all entity types
export type Entity = Assessment | Chat | Feedback | Log | Message | Resume;

// =============================================
// ========== ASSESSMENT TYPES ============
// =============================================

export interface AssessmentQuestion {
  id: string;
  type: 'yes_no' | 'multiple_choice' | 'rating' | 'text';
  question: string;
  options?: string[]; // For multiple choice
  context?: string; // Additional context to display with the question
}

export interface AssessmentResponse {
  question_id: string;
  response: string | number;
}
