// This file is auto-generated by scripts/generate-types.js
// Do not edit this file directly.

import { SupabaseClient } from "@supabase/supabase-js";
import type { Database, Tables } from "@/database.types";

export type TypedSupabaseClient = SupabaseClient<Database>;
export type SchemaName = keyof Database;

// =============================================
// ================ TABLE TYPES ================
// =============================================

// --- CHATS ---
export type Chat = Tables<'chats'>;
// --- LOGS ---
export type Log = Tables<'logs'>;
// --- MESSAGES ---
export type Message = Tables<'messages'>;
