// This file is auto-generated by scripts/generate-types.js
// Do not edit this file directly.

import { SupabaseClient } from "@supabase/supabase-js";
import type { Database, Tables } from "@/database.types";

export type TypedSupabaseClient = SupabaseClient<Database>;
export type SchemaName = keyof Database;

// =============================================
// ================ TABLE TYPES ================
// =============================================

// --- CHATS ---
export type Chat = Tables<'chats'>;
// --- FEEDBACK ---
export type Feedback = Tables<'feedback'>;
// --- LOGS ---
export type Log = Tables<'logs'>;
// --- MESSAGES ---
export type Message = Tables<'messages'>;
// --- RESUMES ---
export type Resume = Tables<'resumes'>;

// =============================================
// ================ ENUM TYPES ================
// =============================================

export type LogLevel = "info" | "error" | "warn" | "debug";
export type MessageRole = "user" | "assistant";

// =============================================
// ============= UTILITY TYPES =============
// =============================================

// Union type of all table names
export type TableName = 'chats' | 'feedback' | 'logs' | 'messages' | 'resumes';

// Union type of all entity types
export type Entity = Chat | Feedback | Log | Message | Resume;
