
-- Add missing columns to trainings table
ALTER TABLE trainings ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT 'Untitled Training';
ALTER TABLE trainings ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE trainings ADD COLUMN IF NOT EXISTS field_ids UUID[];
ALTER TABLE trainings ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT FALSE;
ALTER TABLE trainings ADD COLUMN IF NOT EXISTS preparation BOOLEAN DEFAULT FALSE;


-- Add missing columns to chats table
ALTER TABLE chats ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ NULL;
ALTER TABLE chats ADD COLUMN IF NOT EXISTS completed BOOLEAN DEFAULT FALSE;
ALTER TABLE chats ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE chats ADD COLUMN IF NOT EXISTS trace_id TEXT;
ALTER TABLE chats ADD COLUMN IF NOT EXISTS profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE chats ADD COLUMN IF NOT EXISTS attempt_id UUID REFERENCES attempts(id) ON DELETE CASCADE;

-- Add missing columns to messages table
ALTER TABLE messages ADD COLUMN IF NOT EXISTS chat_id UUID REFERENCES chats(id) ON DELETE CASCADE;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS completed BOOLEAN DEFAULT FALSE;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ NULL;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS error TEXT NULL;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS content TEXT NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN IF NOT EXISTS persona_id UUID REFERENCES personas(id) ON DELETE SET NULL;


-- Add missing columns to assessments table
ALTER TABLE assessments ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT 'Untitled Assessment';
ALTER TABLE assessments ADD COLUMN IF NOT EXISTS chat_id UUID REFERENCES chats(id) ON DELETE CASCADE;


-- Add missing columns to feedback table
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS strengths TEXT[];
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS weaknesses TEXT[];
ALTER TABLE feedback ADD COLUMN IF NOT EXISTS chat_id UUID REFERENCES chats(id) ON DELETE CASCADE;
