#!/usr/bin/env node
/* eslint-disable @typescript-eslint/no-require-imports */

const fs = require('fs');
const path = require('path');

// Import the AST-based schema extractor
const { extractSchema } = require('./ast/extract-schema.js');

// --- Configuration ---

// Define the path for the output file.
const OUTPUT_FILE = path.join(__dirname, '../types.ts');

// Define the path alias to your main database types file.
const DB_TYPES_IMPORT_PATH = '@/database.types';

// Define the path to the actual database types file for parsing
const DB_TYPES_FILE_PATH = path.join(__dirname, '../database.types.ts');

// --- Helper Functions ---

/** Converts a string to PascalCase */
const toPascalCase = (str) =>
    str.replace(/(^\w|-\w|_\w)/g, (c) => c.replace(/[-_]/, '').toUpperCase());

/** Converts a plural table name to its singular form (simple version) */
const toSingular = (tableName) => {
    if (tableName.endsWith('ies')) return tableName.slice(0, -3) + 'y';
    if (tableName.endsWith('s')) return tableName.slice(0, -1);
    return tableName;
};

// This function is no longer needed - replaced by AST-based extraction

// --- Main Generation Logic ---

async function main() {
    console.log('🚀 Generating dynamic database types...');

    try {
        // Use AST-based extraction
        console.log('📖 Using AST-based schema extraction...');
        const { public: { tables }, enums } = extractSchema(DB_TYPES_FILE_PATH);
        const tableNames = Object.keys(tables);

        // Start with the static prefix content
        let content = `// This file is auto-generated by scripts/generate-types.js
// Do not edit this file directly.

import { SupabaseClient } from "@supabase/supabase-js";
import type { Database, Tables } from "${DB_TYPES_IMPORT_PATH}";

export type TypedSupabaseClient = SupabaseClient<Database>;
export type SchemaName = keyof Database;

// =============================================
// ================ TABLE TYPES ================
// =============================================

`;

        // Generate types for each table
        for (const tableName of tableNames) {
            const singularName = toSingular(tableName);
            const pascalName = toPascalCase(singularName);

            content += `// --- ${tableName.toUpperCase()} ---\n`;
            content += `export type ${pascalName} = Tables<'${tableName}'>;\n`;
        }

        // Add enum types
        content += `
// =============================================
// ================ ENUM TYPES ================
// =============================================

`;
        for (const [enumName, values] of Object.entries(enums)) {
            const pascalEnumName = toPascalCase(enumName);
            content += `export type ${pascalEnumName} = ${values.map(v => `"${v}"`).join(' | ')};\n`;
        }

        // Add additional utility types
        content += `
// =============================================
// ============= UTILITY TYPES =============
// =============================================

// Union type of all table names
export type TableName = ${tableNames.map(name => `'${name}'`).join(' | ')};

// Union type of all entity types
export type Entity = ${tableNames.map(name => `${toPascalCase(toSingular(name))}`).join(' | ')};
`;

        // Write the final content to the output file
        fs.writeFileSync(OUTPUT_FILE, content);
        console.log(`✅ Successfully generated: ${path.relative(process.cwd(), OUTPUT_FILE)}`);
        console.log(`📊 Generated types for ${tableNames.length} tables: ${tableNames.join(', ')}`);

    } catch (error) {
        console.error('❌ Error generating types file:', error);
        process.exit(1);
    }

    console.log('\n🎉 Dynamic type generation complete!');
}

main();