#!/usr/bin/env node
/* eslint-disable @typescript-eslint/no-require-imports */

const fs = require('fs');
const path = require('path');

// --- Configuration ---

// Define the path for the output file.
const OUTPUT_FILE = path.join(__dirname, '../types.ts');

// Define the path alias to your main database types file.
const DB_TYPES_IMPORT_PATH = '@/database.types';

// Define the path to the actual database types file for parsing
const DB_TYPES_FILE_PATH = path.join(__dirname, '../database.types.ts');

// --- Helper Functions ---

/** Converts a string to PascalCase */
const toPascalCase = (str) =>
    str.replace(/(^\w|-\w|_\w)/g, (c) => c.replace(/[-_]/, '').toUpperCase());

/** Converts a plural table name to its singular form (simple version) */
const toSingular = (tableName) => {
    if (tableName.endsWith('ies')) return tableName.slice(0, -3) + 'y';
    if (tableName.endsWith('s')) return tableName.slice(0, -1);
    return tableName;
};

/** 
 * Dynamically extracts table names from database.types.ts 
 * This parses the TypeScript file to find table definitions
 */
const extractTableNamesFromDatabaseTypes = () => {
    console.log('📖 Reading database types from:', DB_TYPES_FILE_PATH);
    
    if (!fs.existsSync(DB_TYPES_FILE_PATH)) {
        console.error('❌ Database types file not found:', DB_TYPES_FILE_PATH);
        console.error('   Please run: npm run gen:db first to generate database types');
        process.exit(1);
    }
    
    const content = fs.readFileSync(DB_TYPES_FILE_PATH, 'utf8');
    
    // Extract table names from the Tables interface
    // Look for patterns like: tableName: {
    const tablesMatch = content.match(/Tables:\s*{([\s\S]*?)}\s*Views:/);
    
    if (!tablesMatch) {
        console.error('❌ Could not find Tables interface in database types file');
        process.exit(1);
    }
    
    const tablesContent = tablesMatch[1];
    
    // Extract individual table names - look for table definitions (not Row, Insert, Update, etc.)
    // Match pattern: spaces + tableName + : + spaces + {
    const tableMatches = tablesContent.match(/^\s+(\w+):\s*{$/gm);
    
    if (!tableMatches) {
        console.error('❌ Could not find any table definitions');
        process.exit(1);
    }
    
    const tableNames = tableMatches.map(match => {
        const name = match.replace(/^\s+/, '').replace(/:\s*{$/, '').trim();
        return name;
    }).filter(name => !['Row', 'Insert', 'Update', 'Relationships'].includes(name));
    
    console.log('📋 Found tables:', tableNames);
    return tableNames;
};

// --- Main Generation Logic ---

function main() {
    console.log('🚀 Generating dynamic database types...');

    try {
        // Dynamically extract table names from database.types.ts
        const tableNames = extractTableNamesFromDatabaseTypes();

        // Start with the static prefix content
        let content = `// This file is auto-generated by scripts/generate-types.js
// Do not edit this file directly.

import { SupabaseClient } from "@supabase/supabase-js";
import type { Database, Tables } from "${DB_TYPES_IMPORT_PATH}";

export type TypedSupabaseClient = SupabaseClient<Database>;
export type SchemaName = keyof Database;

// =============================================
// ================ TABLE TYPES ================
// =============================================

`;

        // Generate types for each table
        for (const tableName of tableNames) {
            const singularName = toSingular(tableName);
            const pascalName = toPascalCase(singularName);

            content += `// --- ${tableName.toUpperCase()} ---\n`;
            content += `export type ${pascalName} = Tables<'${tableName}'>;\n`;
        }

        // Write the final content to the output file
        fs.writeFileSync(OUTPUT_FILE, content);
        console.log(`✅ Successfully generated: ${path.relative(process.cwd(), OUTPUT_FILE)}`);
        console.log(`📊 Generated types for ${tableNames.length} tables: ${tableNames.join(', ')}`);

    } catch (error) {
        console.error('❌ Error generating types file:', error);
        process.exit(1);
    }

    console.log('\n🎉 Dynamic type generation complete!');
}

main();