#!/usr/bin/env node
/* eslint-disable @typescript-eslint/no-require-imports */

const fs = require('fs');
const path = require('path');

// --- Configuration ---

// Define the path for the output file.
const OUTPUT_FILE = path.join(__dirname, '../types.ts');

// Define the path alias to your main database types file.
const DB_TYPES_IMPORT_PATH = '@/database.types';

// --- Schema Definition ---
// This should match the table names in your database.types.ts file.
const schema = {
    public: {
        tables: {
            chats: {},
            logs: {},
            messages: {},
        },
    },
};

// --- Helper Functions ---

/** Converts a string to PascalCase */
const toPascalCase = (str) =>
    str.replace(/(^\w|-\w|_\w)/g, (c) => c.replace(/[-_]/, '').toUpperCase());

/** Converts a plural table name to its singular form (simple version) */
const toSingular = (tableName) => {
    if (tableName.endsWith('ies')) return tableName.slice(0, -3) + 'y';
    if (tableName.endsWith('s')) return tableName.slice(0, -1);
    return tableName;
};

// --- Main Generation Logic ---

function main() {
    console.log('🚀 Generating strict database types...');

    // Start with the static prefix content
    let content = `// This file is auto-generated by scripts/generate-types.js
// Do not edit this file directly.

import { SupabaseClient } from "@supabase/supabase-js";
import type { Database, Tables } from "${DB_TYPES_IMPORT_PATH}";

export type TypedSupabaseClient = SupabaseClient<Database>;
export type SchemaName = keyof Database;

// =============================================
// ================ TABLE TYPES ================
// =============================================

`;

    const tableNames = Object.keys(schema.public.tables);

    // Generate types for each table
    for (const tableName of tableNames) {
        const singularName = toSingular(tableName);
        const pascalName = toPascalCase(singularName);

        content += `// --- ${tableName.toUpperCase()} ---\n`;
        content += `export type ${pascalName} = Tables<'${tableName}'>;\n`;
    }

    // Write the final content to the output file
    try {
        fs.writeFileSync(OUTPUT_FILE, content);
        console.log(`✅ Successfully generated: ${path.relative(process.cwd(), OUTPUT_FILE)}`);
    } catch (error) {
        console.error('❌ Error writing types file:', error);
    }

    console.log('\n🎉 Type generation complete!');
}

main();